package com.ptitmeet.common.exception;

import lombok.Getter;

@Getter
public enum ErrorCode {
    SUCCESS(1000, "Success", 200),
    VALIDATION_FAILED(4000, "VALIDATION_FAILED", 400),
    UNAUTHORIZED(4010, "UNAUTHORIZED", 401),
    JWT_EXPIRED(4011, "JWT_EXPIRED", 401),
    REFRESH_TOKEN_INVALID(4012, "REFRESH_TOKEN_INVALID", 401),
    FORBIDDEN(4030, "FORBIDDEN", 403),
    ONLY_OWNER(4031, "ONLY_OWNER_ALLOWED", 403),
    ONLY_HOST(4032, "ONLY_HOST_ALLOWED", 403),
    MEETING_NOT_FOUND(4041, "MEETING_NOT_FOUND", 404),
    USER_NOT_FOUND(4042, "USER_NOT_FOUND", 404),
    RECORDING_NOT_FOUND(4043, "RECORDING_NOT_FOUND", 404),
    PARTICIPANT_NOT_FOUND(4044, "PARTICIPANT_NOT_FOUND", 404),
    EMAIL_ALREADY_EXISTS(4091, "EMAIL_ALREADY_EXISTS", 409),
    FEEDBACK_ALREADY_SUBMITTED(4092, "FEEDBACK_ALREADY_SUBMITTED", 409),
    MEETING_NOT_ACTIVE(4093, "MEETING_NOT_ACTIVE_OR_CANCELED", 409),
    MEETING_NOT_STARTED(4220, "MEETING_NOT_STARTED_YET", 422),
    WRONG_PASSWORD(4221, "WRONG_MEETING_PASSWORD", 422),
    ACCESS_DENIED(4222, "ACCESS_DENIED_BY_MEETING_POLICY", 422),
    PARTICIPANT_KICKED(4223, "PARTICIPANT_WAS_KICKED", 422),
    RECORDING_ALREADY_RUNNING(4224, "RECORDING_ALREADY_RUNNING", 422),
    INTERNAL_SERVER_ERROR(5000, "INTERNAL_SERVER_ERROR", 500),
    SERVICE_UNAVAILABLE(5001, "SERVICE_UNAVAILABLE", 503),
    LIVEKIT_ERROR(5002, "LIVEKIT_CONNECTION_ERROR", 500),
    STORAGE_ERROR(5003, "FILE_STORAGE_ERROR", 500);

    private final int code;
    private final String message;
    private final int httpStatus;

    ErrorCode(int code, String message, int httpStatus) {
        this.code = code;
        this.message = message;
        this.httpStatus = httpStatus;
    }
}
