server:
  port: 8083

spring:
  application:
    name: chat-service
  config:
    import: optional:file:../.env[.properties]
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ptitmeet_chat_db

logging:
  level:
    com.ptitmeet.chat: DEBUG

grpc:
  server:
    port: 9083

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
